language: java
jdk: oraclejdk8
sudo: required
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn clean package
after_success:
  - sudo docker build -t test:$TRAVIS_BUILD_NUMBER .
  - eval $(aws ecr get-login --region eu-central-1)
  - chmod +x scripts/deploy.sh
  - scripts/deploy.sh
services:
  - docker
before_install:
  - pyenv install 3.6.6
  - pyenv global 3.6.6
  - pip3 install awscli --upgrade --user
  - pip3 install awsebcli --upgrade --user
  - export PATH=$PATH:$HOME/.local/bin
env:
  global:
    - secure: tHMj9/MKYyMSfwMS+qgsMpvexhptiZ7b/MuqC1wLfFnlnjJQ4c/OLjqvU1bccsE+TjIg8tbL1TqqGBJlhkwoTxSdG3wxQgRMF+9Kdtl5TJXN3WgA5aZvrJT8+R+TTyQ5HY/652oFRMFDIjLSMvkRADcGA740KcBEL0B17vCB0Rq8C/8AXFiJrHLYSSXBzkgBwaB/gvnS7ltq3fzmuG1oPHMymUdgS6vpniApzKDVUUhHXdmRSEnvHvtqFW8SeqxZRe389dbWwdAhiwJALeKz/9fDzyn6Q/ZmSZTa+fEMHO1NYdUrEeApchTA8iKDUnFxL+Gw9JwPhDdUdmgknxXKPG1EMVd4BmWX+sImra69sR6p2RXuwZaJpTNAUUBbt/T4lvLcZ8viaczLp2v9VA3UbgWirSLVxw0fQO4qeRdb/D3W7ALOK89fm8aujxiuynD8j5gS2zgAF7nPfg3mUfD2h0bflRkUA4o3i8lpXWOpVm1HETZ8d9S2u1If7xW2T+Bh5HJD9j6TRYGGEr1+G9UrhrygT3E0zyYtwF+RtdOjoqOLeBqRMeGsbAwKrO4UHLbrjYBJK7eGPnjb4fCidsUHb5IrexRDOqpzEjcsgfR/tZM3D/gcz8aMxD8UpCciAZICAViT8LEeK+hKKfgQO+92vD8QHpA/YXAb71a65Lzf/cs=
    - secure: d749PEopelObOFgSz7CduJptZHB+Iuy16K9TzCt15wYHqP0ynK4tIAQxwELKmb7bi86oard6rlZxpQ6Q4alzvrE0Hvp0IAWFkJpy3IIq3p3aYvSBNKdgn2gU2qRIKoQBo4JFy6rJckItDeO7NO7lYo/mIHuOvqQHLQXbQaj61cXVJnvx5DZWjwV4XcJjoUlCQTU9++zQGl6R9YtlKKJrhSD05//1oIAe5TApOOO7z0ESm/9vHFahHgMW/vSBkkmnhIxIHw4T/PVtxYK1Lq1CSYXwdJCyE/9mAHC7QLEg7RKhJuGJS8bbWB5BlOYm3JPc5LgJfoiaE26uG65uQj+oJHVVwOK6xlalkOH1r6rwOCV2VP/W12EcRMOayVk+ewxKtBxsyY/b2T560+jXjYAPASyydtqxXOJKOTiYrfKdgNQZH+FSp/pkSOqqFaHmxrsYXdcCEpGBuz4K5mtLNRa/j9qnStnBFZRoOxsYR6eLOHktGBo0KbsExTpOkrKFwQa+leHW3kOXKCBaxcOc90CF8s+NpNF8kIt0XQskFgeNyhjr+LQRm3BKHE1PuFXM4IlYZ6Y/sNXPSkWtpM8INdBEi8M0LIbuMu+O7fqCd3lxJCgibFSsjsp0eTE/KCSeefIJZkVRi9CTpC90mfCcEmJBjzqlWIQ+2khUci2om5zZY4U=
