language: java
jdk: oraclejdk8
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -B
deploy:
  provider: heroku
  api_key:
    secure: Jc9VH6BupQfeKvJsaA1DB5Vb+Xohi6HtGHjRBDIpQCQuqn+y3sZ+aRyv/gzrP1FbpbD33Q4AMdM8AY1S9FK0E9uxyRsLExDneLnLFEaCfE1JtBwSM3oZYr6Sw3iJ68oF9tUjPeyVjQFp32vjAiFSakyYEQJ2hjl8PmnKap1ACmmZJCp4cgeSLq3PM4AnU6eUpbjH4m+d/R/loNOQ9PU9TgUmMb7slL6C1wAH4UGLuDlqR/lyGE1xG1aifm7C5K5qIBE8FssUN5W8UlmSsztPvr7dOzwppZC2GOkIFrTrdUKJXWzZQ0TEpavauUSIVSWgzlxi/G09vIMHryJyknnelvZVb7NQCNake19m1wv19EC6U2ScLvsqsmORfRimvE6nXQxoJphxg2Q/yqIBrGmapFjmLvvchtSK1k8U7mmOghxetQXRbgICh3EPgYcZh2iO5CE1jL4pOUljsRQRL2tXeVhQJ8fj3fDIt8iBN1SVK7H+Zf28R0xaqLfwjp1SovVxkhBPtHLu7kbARjT5kIpGCDB2+CSuyBGQyTXQ8DsZ9+iE3Zb/wprCVMm4jlREtm8wXX+NX2xaUrmPJ/ecqI0AajAyG9t3HAZKZcvJajjvrV7EYfZWWk4xD+oCSxUT2IrsNlDz5RxcUVgdh8aFMi33ZlctmRwkpiMsw7ymys8Uq5w=
  app:
    master: ehomemetro
    develop: ehomedevbranch
  on:
    repo: Ngocvovn/eHome
